# Generated by Django 4.1.7 on 2023-07-27 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='default_thumbnail.jpg', upload_to=None, verbose_name='썸네일'),
        ),
    ]
